// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAgent = `-- name: CreateAgent :one

INSERT INTO agents (name, description, system_prompt, model, tools, team_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, system_prompt, model, tools, team_id, created_by, created_at, updated_at
`

type CreateAgentParams struct {
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	SystemPrompt string                `json:"system_prompt"`
	Model        sql.NullString        `json:"model"`
	Tools        pqtype.NullRawMessage `json:"tools"`
	TeamID       uuid.NullUUID         `json:"team_id"`
	CreatedBy    uuid.NullUUID         `json:"created_by"`
}

// backend/db/queries/agents.sql
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.Model,
		arg.Tools,
		arg.TeamID,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Model,
		&i.Tools,
		&i.TeamID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, description, system_prompt, model, tools, team_id, created_by, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Model,
		&i.Tools,
		&i.TeamID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByTeam = `-- name: ListAgentsByTeam :many
SELECT id, name, description, system_prompt, model, tools, team_id, created_by, created_at, updated_at FROM agents
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByTeam(ctx context.Context, teamID uuid.NullUUID) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.Model,
			&i.Tools,
			&i.TeamID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $2, description = $3, system_prompt = $4, model = $5, tools = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, system_prompt, model, tools, team_id, created_by, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           uuid.UUID             `json:"id"`
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	SystemPrompt string                `json:"system_prompt"`
	Model        sql.NullString        `json:"model"`
	Tools        pqtype.NullRawMessage `json:"tools"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.Model,
		arg.Tools,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Model,
		&i.Tools,
		&i.TeamID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
