// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communities.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCommunity = `-- name: CreateCommunity :one
INSERT INTO communities (name, title, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, title, description, banner_url, icon_url, is_private, created_by, created_at
`

type CreateCommunityParams struct {
	Name        string         `json:"name"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) (Community, error) {
	row := q.db.QueryRowContext(ctx, createCommunity,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommunity = `-- name: DeleteCommunity :exec
DELETE FROM communities WHERE id = $1
`

func (q *Queries) DeleteCommunity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommunity, id)
	return err
}

const getCommunityByID = `-- name: GetCommunityByID :one
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM communities WHERE id = $1
`

func (q *Queries) GetCommunityByID(ctx context.Context, id uuid.UUID) (Community, error) {
	row := q.db.QueryRowContext(ctx, getCommunityByID, id)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCommunityByName = `-- name: GetCommunityByName :one
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM communities WHERE name = $1
`

func (q *Queries) GetCommunityByName(ctx context.Context, name string) (Community, error) {
	row := q.db.QueryRowContext(ctx, getCommunityByName, name)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCommunityMember = `-- name: GetCommunityMember :one
SELECT user_id, community_id, role, joined_at FROM community_members
WHERE user_id = $1 AND community_id = $2
`

type GetCommunityMemberParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CommunityID uuid.UUID `json:"community_id"`
}

func (q *Queries) GetCommunityMember(ctx context.Context, arg GetCommunityMemberParams) (CommunityMember, error) {
	row := q.db.QueryRowContext(ctx, getCommunityMember, arg.UserID, arg.CommunityID)
	var i CommunityMember
	err := row.Scan(
		&i.UserID,
		&i.CommunityID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getCommunityMemberCount = `-- name: GetCommunityMemberCount :one
SELECT COUNT(*) FROM community_members WHERE community_id = $1
`

func (q *Queries) GetCommunityMemberCount(ctx context.Context, communityID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCommunityMemberCount, communityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCommunities = `-- name: GetUserCommunities :many
SELECT c.id, c.name, c.title, c.description, c.banner_url, c.icon_url, c.is_private, c.created_by, c.created_at FROM communities c
JOIN community_members cm ON cm.community_id = c.id
WHERE cm.user_id = $1
ORDER BY cm.joined_at DESC
`

func (q *Queries) GetUserCommunities(ctx context.Context, userID uuid.UUID) ([]Community, error) {
	rows, err := q.db.QueryContext(ctx, getUserCommunities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Community
	for rows.Next() {
		var i Community
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.IconUrl,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserMember = `-- name: IsUserMember :one
SELECT EXISTS (
    SELECT 1 FROM community_members
    WHERE user_id = $1 AND community_id = $2
) AS is_member
`

type IsUserMemberParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CommunityID uuid.UUID `json:"community_id"`
}

func (q *Queries) IsUserMember(ctx context.Context, arg IsUserMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserMember, arg.UserID, arg.CommunityID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const joinCommunity = `-- name: JoinCommunity :exec
INSERT INTO community_members (user_id, community_id, role)
VALUES ($1, $2, 'member')
ON CONFLICT (user_id, community_id) DO NOTHING
`

type JoinCommunityParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CommunityID uuid.UUID `json:"community_id"`
}

func (q *Queries) JoinCommunity(ctx context.Context, arg JoinCommunityParams) error {
	_, err := q.db.ExecContext(ctx, joinCommunity, arg.UserID, arg.CommunityID)
	return err
}

const leaveCommunity = `-- name: LeaveCommunity :exec
DELETE FROM community_members
WHERE user_id = $1 AND community_id = $2
`

type LeaveCommunityParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CommunityID uuid.UUID `json:"community_id"`
}

func (q *Queries) LeaveCommunity(ctx context.Context, arg LeaveCommunityParams) error {
	_, err := q.db.ExecContext(ctx, leaveCommunity, arg.UserID, arg.CommunityID)
	return err
}

const listCommunities = `-- name: ListCommunities :many
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM communities
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCommunitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]Community, error) {
	rows, err := q.db.QueryContext(ctx, listCommunities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Community
	for rows.Next() {
		var i Community
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.IconUrl,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityMembers = `-- name: ListCommunityMembers :many
SELECT u.id, u.username, u.avatar_url, cm.role, cm.joined_at
FROM community_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.community_id = $1
ORDER BY cm.joined_at DESC
LIMIT $2 OFFSET $3
`

type ListCommunityMembersParams struct {
	CommunityID uuid.UUID `json:"community_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListCommunityMembersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Role      sql.NullString `json:"role"`
	JoinedAt  sql.NullTime   `json:"joined_at"`
}

func (q *Queries) ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityMembers, arg.CommunityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunityMembersRow
	for rows.Next() {
		var i ListCommunityMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommunity = `-- name: UpdateCommunity :one
UPDATE communities
SET title = $2, description = $3
WHERE id = $1
RETURNING id, name, title, description, banner_url, icon_url, is_private, created_by, created_at
`

type UpdateCommunityParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateCommunity(ctx context.Context, arg UpdateCommunityParams) (Community, error) {
	row := q.db.QueryRowContext(ctx, updateCommunity, arg.ID, arg.Title, arg.Description)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
