// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (run_id, sequence, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, sequence, type, payload, created_at
`

type CreateEventParams struct {
	RunID    uuid.UUID       `json:"run_id"`
	Sequence int32           `json:"sequence"`
	Type     string          `json:"type"`
	Payload  json.RawMessage `json:"payload"`
}

// backend/db/queries/events.sql
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.RunID,
		arg.Sequence,
		arg.Type,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSequence = `-- name: GetLatestSequence :one
SELECT COALESCE(MAX(sequence), 0) FROM events WHERE run_id = $1
`

func (q *Queries) GetLatestSequence(ctx context.Context, runID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestSequence, runID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listEventsByRun = `-- name: ListEventsByRun :many
SELECT id, run_id, sequence, type, payload, created_at FROM events
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListEventsByRun(ctx context.Context, runID uuid.UUID) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
