// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Agent struct {
	ID           uuid.UUID             `json:"id"`
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	SystemPrompt string                `json:"system_prompt"`
	Model        sql.NullString        `json:"model"`
	Tools        pqtype.NullRawMessage `json:"tools"`
	TeamID       uuid.NullUUID         `json:"team_id"`
	CreatedBy    uuid.NullUUID         `json:"created_by"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type Event struct {
	ID        uuid.UUID       `json:"id"`
	RunID     uuid.UUID       `json:"run_id"`
	Sequence  int32           `json:"sequence"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt sql.NullTime    `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Run struct {
	ID          uuid.UUID      `json:"id"`
	AgentID     uuid.UUID      `json:"agent_id"`
	TeamID      uuid.UUID      `json:"team_id"`
	StartedBy   uuid.UUID      `json:"started_by"`
	Status      sql.NullString `json:"status"`
	Input       string         `json:"input"`
	Output      sql.NullString `json:"output"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type Team struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	BannerUrl   sql.NullString `json:"banner_url"`
	IconUrl     sql.NullString `json:"icon_url"`
	IsPrivate   sql.NullBool   `json:"is_private"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type TeamMember struct {
	UserID   uuid.UUID      `json:"user_id"`
	TeamID   uuid.UUID      `json:"team_id"`
	Role     sql.NullString `json:"role"`
	JoinedAt sql.NullTime   `json:"joined_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	IsBanned  sql.NullBool   `json:"is_banned"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
