// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID     `json:"id"`
	Body      string        `json:"body"`
	Score     sql.NullInt32 `json:"score"`
	PostID    uuid.NullUUID `json:"post_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	IsRemoved sql.NullBool  `json:"is_removed"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Community struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	BannerUrl   sql.NullString `json:"banner_url"`
	IconUrl     sql.NullString `json:"icon_url"`
	IsPrivate   sql.NullBool   `json:"is_private"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type CommunityMember struct {
	UserID      uuid.UUID      `json:"user_id"`
	CommunityID uuid.UUID      `json:"community_id"`
	Role        sql.NullString `json:"role"`
	JoinedAt    sql.NullTime   `json:"joined_at"`
}

type ModAction struct {
	ID          uuid.UUID      `json:"id"`
	ModeratorID uuid.NullUUID  `json:"moderator_id"`
	TargetID    uuid.UUID      `json:"target_id"`
	Target      string         `json:"target"`
	Action      string         `json:"action"`
	Reason      sql.NullString `json:"reason"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Post struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Body         sql.NullString `json:"body"`
	Url          sql.NullString `json:"url"`
	Type         string         `json:"type"`
	Score        sql.NullInt32  `json:"score"`
	CommentCount sql.NullInt32  `json:"comment_count"`
	CommunityID  uuid.NullUUID  `json:"community_id"`
	AuthorID     uuid.NullUUID  `json:"author_id"`
	Embedding    interface{}    `json:"embedding"`
	IsRemoved    sql.NullBool   `json:"is_removed"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	IsBanned  sql.NullBool   `json:"is_banned"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type UserEmbedding struct {
	UserID    uuid.UUID    `json:"user_id"`
	Embedding interface{}  `json:"embedding"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Vote struct {
	UserID    uuid.UUID    `json:"user_id"`
	TargetID  uuid.UUID    `json:"target_id"`
	Target    string       `json:"target"`
	Direction int16        `json:"direction"`
	CreatedAt sql.NullTime `json:"created_at"`
}
