// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (agent_id, team_id, started_by, input)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_id, team_id, started_by, status, input, output, started_at, completed_at
`

type CreateRunParams struct {
	AgentID   uuid.UUID `json:"agent_id"`
	TeamID    uuid.UUID `json:"team_id"`
	StartedBy uuid.UUID `json:"started_by"`
	Input     string    `json:"input"`
}

// backend/db/queries/runs.sql
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.AgentID,
		arg.TeamID,
		arg.StartedBy,
		arg.Input,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TeamID,
		&i.StartedBy,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, agent_id, team_id, started_by, status, input, output, started_at, completed_at FROM runs WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id uuid.UUID) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TeamID,
		&i.StartedBy,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRunsByAgent = `-- name: ListRunsByAgent :many
SELECT id, agent_id, team_id, started_by, status, input, output, started_at, completed_at FROM runs
WHERE agent_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByAgentParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListRunsByAgent(ctx context.Context, arg ListRunsByAgentParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.StartedBy,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByTeam = `-- name: ListRunsByTeam :many
SELECT id, agent_id, team_id, started_by, status, input, output, started_at, completed_at FROM runs
WHERE team_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListRunsByTeamParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRunsByTeam(ctx context.Context, arg ListRunsByTeamParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByTeam, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.StartedBy,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs
SET status = $2, output = $3, completed_at = NOW()
WHERE id = $1
RETURNING id, agent_id, team_id, started_by, status, input, output, started_at, completed_at
`

type UpdateRunStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
	Output sql.NullString `json:"output"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, updateRunStatus, arg.ID, arg.Status, arg.Output)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TeamID,
		&i.StartedBy,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
