// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name, title, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, title, description, banner_url, icon_url, is_private, created_by, created_at
`

type CreateTeamParams struct {
	Name        string         `json:"name"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
}

// backend/db/queries/teams.sql
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM teams WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT user_id, team_id, role, joined_at FROM team_members
WHERE user_id = $1 AND team_id = $2
`

type GetTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMember, arg.UserID, arg.TeamID)
	var i TeamMember
	err := row.Scan(
		&i.UserID,
		&i.TeamID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamMemberCount = `-- name: GetTeamMemberCount :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1
`

func (q *Queries) GetTeamMemberCount(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberCount, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT t.id, t.name, t.title, t.description, t.banner_url, t.icon_url, t.is_private, t.created_by, t.created_at FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY tm.joined_at DESC
`

func (q *Queries) GetUserTeams(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.IconUrl,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserMember = `-- name: IsUserMember :one
SELECT EXISTS (
    SELECT 1 FROM team_members
    WHERE user_id = $1 AND team_id = $2
) AS is_member
`

type IsUserMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) IsUserMember(ctx context.Context, arg IsUserMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserMember, arg.UserID, arg.TeamID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const joinTeam = `-- name: JoinTeam :exec
INSERT INTO team_members (user_id, team_id, role)
VALUES ($1, $2, 'member')
ON CONFLICT (user_id, team_id) DO NOTHING
`

type JoinTeamParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) JoinTeam(ctx context.Context, arg JoinTeamParams) error {
	_, err := q.db.ExecContext(ctx, joinTeam, arg.UserID, arg.TeamID)
	return err
}

const leaveTeam = `-- name: LeaveTeam :exec
DELETE FROM team_members
WHERE user_id = $1 AND team_id = $2
`

type LeaveTeamParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) LeaveTeam(ctx context.Context, arg LeaveTeamParams) error {
	_, err := q.db.ExecContext(ctx, leaveTeam, arg.UserID, arg.TeamID)
	return err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.username, u.avatar_url, tm.role, tm.joined_at
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.joined_at DESC
LIMIT $2 OFFSET $3
`

type ListTeamMembersParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListTeamMembersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Role      sql.NullString `json:"role"`
	JoinedAt  sql.NullTime   `json:"joined_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, title, description, banner_url, icon_url, is_private, created_by, created_at FROM teams
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTeamsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.BannerUrl,
			&i.IconUrl,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET title = $2, description = $3
WHERE id = $1
RETURNING id, name, title, description, banner_url, icon_url, is_private, created_by, created_at
`

type UpdateTeamParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.ID, arg.Title, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.BannerUrl,
		&i.IconUrl,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
